version: '3.4'

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongo_data:
  sqldb:
   
networks:
  default:    
    name: mydockernetwork
    external: true

services:
  sqlDB:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
    container_name: sqlDB
    environment:
        SA_PASSWORD: "Password$1234"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
    restart: always
    ports:
        - "5544:1433"
    volumes:
        - sqldb:/var/opt/mssql

  mongoDB:
    image: mongo:latest
    container_name: mongoDB
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
   
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kakfa-manager
    restart: always
    ports:
        - "9000:9000"
    depends_on:
        - zookeeper
        - kafka
    environment:
        ZK_HOSTS: "zookeeper:2181"
        APPLICATION_SECRET: "random-secret"
        command: -Dpidfile.path=/dev/null
